name: example
description: stream_loader example
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  built_value: ^7.1.0
  flutter_provider: ^1.1.1
  stream_loader:

dev_dependencies:
  pedantic: ^1.9.0
  built_value_generator: ^7.1.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  stream_loader:
    path: ../
