name: example
description: stream_loader example
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.4
  built_value: ^8.4.0
  flutter_provider: ^2.1.0
  built_collection: ^5.1.1
  stream_loader:

dev_dependencies:
  flutter_lints: ^2.0.1
  built_value_generator: ^8.4.0
  build_runner: ^2.2.0
  quiver: ^3.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  stream_loader:
    path: ../
