name: stream_loader
description: A flutter plugin for loading content asynchronously with Dart stream.
version: 1.1.0-nullsafety.0
homepage: https://github.com/hoc081098/stream_loader.git
repository: https://github.com/hoc081098/stream_loader.git
issue_tracker: https://github.com/hoc081098/stream_loader/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  disposebag: ^1.5.0-nullsafety.0
  distinct_value_connectable_stream: ^1.2.0-nullsafety.2
  rxdart_ext: ^0.0.1-nullsafety.2
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  flutter_test:
    sdk: flutter
