name: stream_loader
description: A flutter plugin for loading content asynchronously with Dart stream. RxDart loader bloc.
version: 1.4.0
homepage: https://github.com/hoc081098/stream_loader.git
repository: https://github.com/hoc081098/stream_loader.git
issue_tracker: https://github.com/hoc081098/stream_loader/issues

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  disposebag: ^1.5.0
  rxdart_ext: ^0.2.0
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  mockito: ^5.0.16
  flutter_lints: ^1.0.4
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
