name: stream_loader
description: A flutter plugin for loading content asynchronously with Dart stream. RxDart loader bloc.
version: 1.1.0
homepage: https://github.com/hoc081098/stream_loader.git
repository: https://github.com/hoc081098/stream_loader.git
issue_tracker: https://github.com/hoc081098/stream_loader/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  disposebag: ^1.5.0
  distinct_value_connectable_stream: ^1.2.0
  rxdart_ext: ^0.0.1
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  mockito: ^5.0.3
  pedantic: ^1.11.0
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
