name: stream_loader
description: A flutter plugin for loading content asynchronously with Dart stream.
version: 1.1.0-beta02
homepage: https://github.com/hoc081098/stream_loader.git
repository: https://github.com/hoc081098/stream_loader.git
issue_tracker: https://github.com/hoc081098/stream_loader/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  disposebag: ^1.4.0
  distinct_value_connectable_stream: ^1.2.0-beta02
  rxdart: ^0.25.0
  built_value: ^7.1.0
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  mockito: ^4.1.2
  pedantic: ^1.9.2
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
  flutter_test:
    sdk: flutter
