name: stream_loader
description: A flutter plugin for loading content asynchronously.
version: 0.0.1
homepage: https://github.com/hoc081098/stream_loader.git

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  disposebag: ^1.0.0+1
  distinct_value_connectable_stream: ^1.0.3
  rxdart: ^0.23.1
  built_value: ^7.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  build_runner: ^1.0.0
  built_value_generator: ^7.0.0
  flutter_test:
    sdk: flutter

flutter:
