name: stream_loader
description: A Flutter plugin for loading content asynchronously with Dart stream and RxDart. RxDart loader bloc. Reactive loader bloc. Simple reactive state management container.
version: 1.5.0
homepage: https://github.com/hoc081098/stream_loader.git
repository: https://github.com/hoc081098/stream_loader.git
issue_tracker: https://github.com/hoc081098/stream_loader/issues

environment:
  sdk: '<4.0.0'
  flutter: '>=3.0.0'

dependencies:
  disposebag: ^1.5.1
  rxdart_ext: ^0.2.5
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  mockito: ^5.2.0
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  analyzer: ^4.1.0
  code_builder: ^4.1.0
  flutter_test:
    sdk: flutter
